# Site settings
title: All about infrastructure software and system programming
description: All about infrastructure software and system programming
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://paul-guo-.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
